version: '3'

services:
  nginxwebui:
    image: cym1102/nginxwebui:latest
    container_name: nginxwebui
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /volume2/docker/docker-compose-config/nginxwebUi:/home/nginxWebUI
    environment:  
      - BOOT_OPTIONS=--server.port=8787
