global:
  scrape_interval:     60s
  evaluation_interval: 60s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['192.168.0.12:9290']
        labels:
          instance: prometheus
 
  - job_name: linux_nas
    static_configs:
      - targets: ['192.168.0.12:9100']
        labels:
          instance: localhost